
NodeModule nodes {

	basic.Boolean config1 @export {
		arg0: true;
	}

	basic.If {
		arg0: $config1;

		basic.Boolean config2 @export {
			arg0: true;
		}

		basic.If {
			arg0: $config2;

			basic.Multiply mul1 @export {
				arg0: 7.0 * 2.0;
				arg1: 6.23;
			}

			basic.Return {
				arg0 : $mul1;
			}
		}
	}

	basic.Float node1 @export {
		arg0 : 5.0;
	}

	basic.Floats numbers1 @export {
		arg0 : 1.0, 2.0, $node1;
	}

	basic.For {
		arg0: $numbers1;
		arg1: numberC;

		basic.Multiply mulFor @export {
			arg0: 2.34;
			arg1: 1.23;
		}
	}

	basic.Return {
		arg0 : $node1;
	}
}