
NodeModule nodes {

	StaticBoolean config1 @export {
		parameters: true;
	}

	If {
		parameters: $config1;

		StaticBoolean config2 @export {
			parameters: false;
		}

		If {
			parameters: $config2;

			Multiply mul1 @export {
				parameters: 7.0, 6.23;
			}

			Return {
				parameters : $mul1;
			}
		}
	}

	StaticFloat node1 @export {
		parameters : 5.0;
	}

	Floats numbers1 @export {
		parameters : 1.0, 2.0, $node1;
	}

/*

	For {
		parameters: $numbers1, numberC;

		Multiply mulFor @export {
			parameters: numberC, $mulFor;
		}
	}
*/

	Return {
		parameters : $numbers1;
	}
}