package de.s42.dlt;

import de.s42.dlt.parser.CompiledTemplate;
import de.s42.dlt.parser.TemplateContext;
import de.s42.base.validation.ValidationHelper;

/*
 * PLEASE DO NOT MODIFY THIS CLASS - IT IS GENERATED BY THE DATA LANGUAGE TEMPLATES COMPILER
 */
public class DLTTestTemplate implements CompiledTemplate
{
@Override
public String evaluate(TemplateContext context) throws Exception
{
//set 6:2
context.setBinding("name","Thorsten");
//set 7:2
context.setBinding("adCampaignTemplate","DLTTest.template.adcampaign.dlt");
//load 8:2
context.load("LOAD_INIT", "de.s42.dlt.DLTTest$LoadInit", new Object[] {context.resolveBinding("TestName")});
//assert 9:2
assert (boolean)context.resolveBinding(new String[] {"user"}, new String[] {"exists"}) : "user has to be set" + " - " + 9 + ":" + 2 + " in 'DLTTest.template.dlt'";
//set 10:2
context.setBinding( new String[] { "user", "firstName"}, new Object[] { "Stefan"});
//set 11:2
context.setBinding("productNameUppercase",context.resolveBinding(new String[] {"productName"}, new String[] {"upperCase"}));
//text 12:0
context.append("Dear ");
//read 12:7
context.append(context.resolveBinding(new String[] {"user", "firstName"}, new String[] {}));
//text 12:22
context.append(",\n\nwelcome to our ");
//read 14:17
context.append(context.resolveBinding("productName"));
//text 14:29
context.append(" Community.\n");
//if 15:2
if (Boolean.TRUE.equals(context.resolveBinding(new String[] {"user", "infos"}, new String[] {"length", "greater0"}))) {
//text 16:0
context.append("\nHere is your favorite ");
//read 17:24
context.append(context.resolveBinding(new String[] {"user", "infos"}, new String[] {"length"}));
//text 17:42
context.append(" infos:\n");
//for 18:2
Object[] var2 = (Object[])context.resolveBinding(new String[] {"user", "infos"}, new String[] {});
if (var2 != null && var2.length > 0) {
int var2Length = var2.length;
context.setBinding("info#first", true);
context.setBinding("info#last", false);
for (int var1 = 0; var1 < var2Length; ++var1) {
context.setBinding("info", var2[var1]);
context.setBinding("info#index", var1);
if (var1 < 2) { context.setBinding("info#first", (var1 == 0)); }
if (var1 > var2Length - 2) { context.setBinding("info#last", (var1 >= var2Length - 1)); }
//text 19:0
context.append("* ");
//read 19:4
context.append(context.resolveBinding("info"));
//if 19:11
if (Boolean.TRUE.equals(context.resolveBinding("info#first"))) {
//text 19:25
context.append(" (TOP Info)");
//end if 19:38
}
//text 19:42
context.append("\n");
//end for 20:2
}
}
//end if 21:2
}
//text 22:0
context.append("\nYour ");
//read 23:7
context.append(context.resolveBinding("productNameUppercase"));
//text 23:28
context.append(" Team\n\n--\n");
//if 26:2
if (Boolean.TRUE.equals(context.resolveBinding("ADCAMPAIGN"))) {
//text 27:0
context.append("\n");
//include 28:2
context.evaluate((String)context.resolveBinding("adCampaignTemplate"));
//text 28:29
context.append("\n");
//else 29:2
} else {
//text 30:0
context.append("\nWe have interesting offers under: www.test.com\n");
//end if 32:2
}
//text 33:0
context.append("\nThis mail was generated at ");
//read 34:29
context.append(context.resolveBinding(new String[] {"now", "iso"}, new String[] {}));
//text 34:37
context.append("\nThe security code is ");
//code 35:24


	// here you can write java code directly if necessary test {escaped brackets}
	//this is as fallback -> better use TemplateCallable or TemplateLoadable
	java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
	String toHash = (String)context.resolveBinding("name");
	md.update(toHash.getBytes());
	String md5Hash = de.s42.base.conversion.ConversionHelper.bytesToHex(md.digest());
	context.setBinding("securityCode", md5Hash);
	context.append(md5Hash);

//section 46:2
context.pushSection("SENDINFO");
//text 47:0
context.append("Recipient: ");
//read 47:13
context.append(context.resolveBinding(new String[] {"user", "firstName"}, new String[] {}));
//text 47:28
context.append("\nAdCampaign: ");
//read 48:14
context.append(context.resolveBinding("ADCAMPAIGN"));
//text 48:25
context.append("\nSecurityCode: ");
//read 49:16
context.append(context.resolveBinding("securityCode"));
//text 49:29
context.append("\nDate: ");
//read 50:8
context.append(context.resolveBinding(new String[] {"now", "iso"}, new String[] {}));
//end section 51:2
context.popSection();
return context.getContent();
}
}